name: lint and test

on:
  push:
    branches:
      - develop
      - master
    tags:
      - "*"
  pull_request:
    branches:
      - develop
      - master

jobs:
  check_skip:
    runs-on: ubuntu-latest

    if: "! startsWith(github.event.head_commit.message, '[CI Skip]') && github.repository == 'kiltprotocol/tx-wrapper'"

    steps:
      - name: Not Skipped
        run: echo "Not Skipped"

  build:
    runs-on: ubuntu-latest

    needs: check_skip

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 14
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'yarn'

      - name: yarn install
        run: yarn install --immutable
      - name: yarn build
        run: yarn build
   
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: run integration tests
        timeout-minutes: 60
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: kilt/prototype-chain
          IMAGE_TAG: latest-rc
        run: |
          docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker run -d --rm -p 9933:9933 $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG --dev --ws-port 9944 --ws-external --rpc-external --rpc-methods=unsafe
          sleep 5s
          yarn test
          docker stop $(docker ps -f ancestor=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -q)
